function createtext(Parent1)
%CREATETEXT(PARENT1)
%  PARENT1:  text parent

%  Auto-generated by MATLAB on 03-Sep-2013 21:20:34

% Create text
text('Parent',Parent1,'Tag','varlabel','String','X6',...
    'Position',[0.0927123459980071 -0.100311513951829 -0.267187412483098], ...
    'FontSize', 24);

